# Generated by Django 5.1.5 on 2025-02-15 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientsStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=50, verbose_name='Название статуса')),
            ],
            options={
                'verbose_name': 'Статус клиента',
                'verbose_name_plural': 'Статусы клиентов',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('project_name', models.CharField(max_length=100, verbose_name='Название проекта')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('photo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Фото')),
                ('contact', models.CharField(max_length=100, verbose_name='Контакт')),
                ('start_date', models.DateField(verbose_name='Дата начала работы')),
                ('status', models.ForeignKey(db_column='status', on_delete=django.db.models.deletion.DO_NOTHING, to='clients.clientsstatus', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsersClients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='clients.clients', verbose_name='Клиент')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь пользователь-клиент',
                'verbose_name_plural': 'Связи пользователь-клиент',
                'db_table': 'users_clients',
                'managed': True,
            },
        ),
    ]
